apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: localhost:5000/helloworld-go:latest
          imagePullPolicy: Never 
          env:
            - name: TARGET
              value: "Go Sample v1"